site_name: PCF Catalog
theme: material
nav:
  - Home: index.md
  - Vision and Strategy: vision_and_strategy/index.md
  - Products and Services: products_and_services/index.md
  - Market and Sell: market_and_sell/index.md
  - Supply Chain: supply_chain/index.md
  - Deliver Services: deliver_services/index.md
  - Customer Service: customer_service/index.md
  - Human Capital: human_capital/index.md
  - Information Technology: information_technology/index.md
  - Financial Resources: financial_resources/index.md
  - Assets: assets/index.md
  - Enterprise Risk: enterprise_risk/index.md
